language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - bharat.kareti@ncs.com.sg
    on_success: always
    on_failure: always
branches:
  only:
   - master
before_script:
  - npm install -g @angular/cli
  - npm install -g now
script:
  - ng build --prod --base-href 
https://bharatkareti95.github.io/bitcoin-order-app/

  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin-order-app
  on:
    branch: master
